export const NICHES = {
  "Medical": "Ambulatory Health Care Services",
  "Bakery": "Retail Bakeries & Baked Goods",
  "Plumbing": "Plumbing & HVAC Contractors",
  "Roofing": "Roofing Contractors",
  "Veterinary": "Veterinary Services",
  "Dental": "Dental Offices",
  "Fitness": "Fitness & Wellness",
  "Legal": "Legal Services",
};

export const COUNTRIES = ["United States", "United Kingdom", "Canada", "Ireland"];

export const leads = [
  // Medical — from Vibe Prospecting
  {
    id: "deddc4ad",
    name: "CTisus",
    domain: "ctisus.com",
    website: "https://ctisus.com",
    logo: "https://media.licdn.com/dms/image/v2/C4E0BAQH2lPFA_iLa7Q/company-logo_200_200/company-logo_200_200/0/1630593945081/ctisus_logo?e=2147483647&v=beta&t=DABSlKfEMCWzc5DtCO_fZYVnYctkEu-ITi_JXO7Q_zw",
    city: "Baltimore",
    region: "Maryland",
    country: "United States",
    niche: "Medical",
    size: "1-10",
    revenue: "500K-1M",
    linkedin: "https://www.linkedin.com/company/ctisus",
    description: "Informational and educational radiological resource dedicated to CT scanning. Website provides latest radiology technology and 3D imaging info.",
    techStack: ["ASP.NET", "Classic ASP", "Google Analytics 4", "Cloudflare", "Hotjar"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "e84f60fb",
    name: "OncoAlert",
    domain: "oncoalert360.com",
    website: "https://www.oncoalert360.com",
    logo: "https://media.licdn.com/dms/image/v2/C4D0BAQGMyU8EtgsM9g/company-logo_200_200/company-logo_200_200/0/1630519363234?e=2147483647&v=beta&t=kH5NxW7D6bSPd6sMWRyte5ByTV_0GIwdmjx9ox7eeYI",
    city: "San Antonio",
    region: "Texas",
    country: "United States",
    niche: "Medical",
    size: "1-10",
    revenue: "500K-1M",
    linkedin: "https://www.linkedin.com/company/oncoalert",
    description: "International network of oncology stakeholders with 150+ faculty of oncologists, nurses, and patient advocates. Built on Weebly.",
    techStack: ["Weebly", "Vue", "jQuery", "Google Analytics", "PayPal"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "45636c2e",
    name: "British Society of Echocardiography",
    domain: "bsecho.org",
    website: "https://www.bsecho.org",
    logo: "https://media.licdn.com/dms/image/v2/D4E0BAQH2pxZzh5Pf2Q/company-logo_200_200/company-logo_200_200/0/1665481610512/british_society_of_echocardiography_logo?e=2147483647&v=beta&t=M137BkB8XNU3GeHfc8IiU4ucXqLTHt8AnprVZGiMM2s",
    city: "Southwark",
    region: "England",
    country: "United Kingdom",
    niche: "Medical",
    size: "11-50",
    revenue: "500K-1M",
    linkedin: "https://www.linkedin.com/company/british-society-of-echocardiography",
    description: "Promotes study of cardiac ultrasound imaging. Membership of cardiac physiologists and clinicians. Site has e-commerce for memberships.",
    techStack: ["ASP.NET", "Digital Ocean", "Cloudflare", "Google Analytics 4"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "f478dd22",
    name: "European Renal Association",
    domain: "era-online.org",
    website: "https://www.era-online.org",
    logo: "https://media.licdn.com/dms/image/v2/C4D0BAQHggrzVYkUZWA/company-logo_200_200/company-logo_200_200/0/1631713613640/europeanrenalassociation_logo?e=2147483647&v=beta&t=qEj2B-ce3fXyxP9OfwPUP1U0OvUTcQO0jowWjkwMEI8",
    city: "London",
    region: "England",
    country: "United Kingdom",
    niche: "Medical",
    size: "11-50",
    revenue: "500K-1M",
    linkedin: "https://www.linkedin.com/company/europeanrenalassociation",
    description: "28,000+ member nephrology association. Supports clinical research in nephrology, dialysis, and renal transplantation.",
    techStack: ["WordPress", "Apache", "Amazon CloudFront", "Google Analytics 4"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "d8009fd7",
    name: "Society of Occupational Medicine",
    domain: "som.org.uk",
    website: "https://www.som.org.uk",
    logo: "https://media.licdn.com/dms/image/v2/C4E0BAQFtbdo-C74S6g/company-logo_200_200/company-logo_200_200/0/1630571289003/society_of_occupational_medicine_logo?e=2147483647&v=beta&t=x3pMA-SN2l9dvKN60MoCpBjwIGA-OxlM-2ecr3O-pnQ",
    city: "London",
    region: "England",
    country: "United Kingdom",
    niche: "Medical",
    size: "11-50",
    revenue: "500K-1M",
    linkedin: "https://www.linkedin.com/company/society-of-occupational-medicine",
    description: "Registered charity improving health of working-age population across UK. Built on Drupal 7 — an outdated CMS version.",
    techStack: ["Drupal 7", "CiviCRM", "nginx", "Google Analytics"],
    hasWebsite: true,
    analysis: null,
  },
  // Bakery leads
  {
    id: "bak001",
    name: "The Flour Pot Bakery",
    domain: "flourpotbakery.co.uk",
    website: "https://www.flourpotbakery.co.uk",
    logo: null,
    city: "Brighton",
    region: "England",
    country: "United Kingdom",
    niche: "Bakery",
    size: "1-10",
    revenue: "500K-1M",
    linkedin: null,
    description: "Artisan bakery and café in Brighton. Serves pastries, sourdough, sandwiches. Local community favourite with 4 locations.",
    techStack: ["Squarespace", "Google Analytics"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "bak002",
    name: "Levee Bakehouse",
    domain: null,
    website: null,
    logo: null,
    city: "Toronto",
    region: "Ontario",
    country: "Canada",
    niche: "Bakery",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Small artisan bakehouse in Toronto. Known for croissants and natural fermentation bread. No website presence found.",
    techStack: [],
    hasWebsite: false,
    analysis: null,
  },
  {
    id: "bak003",
    name: "Celtic Crumb Bakery",
    domain: "celticcrumbbakery.ie",
    website: "https://celticcrumbbakery.ie",
    logo: null,
    city: "Dublin",
    region: "Leinster",
    country: "Ireland",
    niche: "Bakery",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Family-run Irish bakery in Dublin. Sells traditional soda bread, scones, and celebration cakes. Website is basic HTML, not mobile-optimised.",
    techStack: ["Basic HTML", "No analytics"],
    hasWebsite: true,
    analysis: null,
  },
  // Plumbing leads
  {
    id: "plumb001",
    name: "RapidFlow Plumbing",
    domain: null,
    website: null,
    logo: null,
    city: "Manchester",
    region: "England",
    country: "United Kingdom",
    niche: "Plumbing",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Local emergency plumbing service covering Greater Manchester. No website — only found on Checkatrade and Yell.com.",
    techStack: [],
    hasWebsite: false,
    analysis: null,
  },
  {
    id: "plumb002",
    name: "AquaPro Services",
    domain: "aquaproservices.ca",
    website: "https://aquaproservices.ca",
    logo: null,
    city: "Vancouver",
    region: "British Columbia",
    country: "Canada",
    niche: "Plumbing",
    size: "1-10",
    revenue: "500K-1M",
    linkedin: null,
    description: "Residential and commercial plumbing in Vancouver. Website is a basic Wix template from 2018. No lead capture forms.",
    techStack: ["Wix", "No SSL", "No analytics"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "plumb003",
    name: "Cork City Plumbers",
    domain: "corkcityplumbers.ie",
    website: "https://corkcityplumbers.ie",
    logo: null,
    city: "Cork",
    region: "Munster",
    country: "Ireland",
    niche: "Plumbing",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Family plumbing business serving Cork City and County. Google reviews: 4.2★ (18 reviews). Website has no contact form or online booking.",
    techStack: ["WordPress", "Divi Theme"],
    hasWebsite: true,
    analysis: null,
  },
  // Roofing leads
  {
    id: "roof001",
    name: "Peak Roofing Solutions",
    domain: "peakroofingsolutions.com",
    website: "https://peakroofingsolutions.com",
    logo: null,
    city: "Denver",
    region: "Colorado",
    country: "United States",
    niche: "Roofing",
    size: "1-10",
    revenue: "500K-1M",
    linkedin: null,
    description: "Residential roofing contractor in Denver metro. Specialises in hail damage repair and new roof installations. Website uses an old Joomla template.",
    techStack: ["Joomla", "Google Analytics", "No SSL"],
    hasWebsite: true,
    analysis: null,
  },
  {
    id: "roof002",
    name: "Skyline Roofing Co.",
    domain: null,
    website: null,
    logo: null,
    city: "Birmingham",
    region: "England",
    country: "United Kingdom",
    niche: "Roofing",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Local roofing contractor in Birmingham. Handles flat roofs, tiles, and fascias. Listed only on local directories with no web presence.",
    techStack: [],
    hasWebsite: false,
    analysis: null,
  },
  {
    id: "roof003",
    name: "Northern Shield Roofing",
    domain: "northernshieldroofing.ca",
    website: "https://northernshieldroofing.ca",
    logo: null,
    city: "Calgary",
    region: "Alberta",
    country: "Canada",
    niche: "Roofing",
    size: "11-50",
    revenue: "1M-5M",
    linkedin: "https://linkedin.com/company/northern-shield-roofing",
    description: "Established roofing company in Calgary. Services residential and commercial clients. Website is functional but lacks SEO, testimonials page, and has slow load times.",
    techStack: ["WordPress", "WooCommerce", "Cloudflare"],
    hasWebsite: true,
    analysis: null,
  },
  // Dental
  {
    id: "dent001",
    name: "Smile Studio Dublin",
    domain: null,
    website: null,
    logo: null,
    city: "Dublin",
    region: "Leinster",
    country: "Ireland",
    niche: "Dental",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "General and cosmetic dentistry practice in Dublin 2. 4.7★ on Google (44 reviews). No website — patients find them purely via Google Maps.",
    techStack: [],
    hasWebsite: false,
    analysis: null,
  },
  {
    id: "dent002",
    name: "Bright Smiles Dental",
    domain: "brightsmilesdental.co.uk",
    website: "https://brightsmilesdental.co.uk",
    logo: null,
    city: "Leeds",
    region: "England",
    country: "United Kingdom",
    niche: "Dental",
    size: "1-10",
    revenue: "500K-1M",
    linkedin: null,
    description: "NHS and private dental practice in Leeds. Website is 6 years old, not mobile-responsive. Patient portal is a third-party iFrame that looks broken on mobile.",
    techStack: ["HTML4", "No SSL on subpages", "No analytics"],
    hasWebsite: true,
    analysis: null,
  },
  // Fitness
  {
    id: "fit001",
    name: "Iron & Oak Gym",
    domain: null,
    website: null,
    logo: null,
    city: "Austin",
    region: "Texas",
    country: "United States",
    niche: "Fitness",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Independent strength and conditioning gym in Austin. Strong Instagram presence but no website. Members book via a shared Google Calendar link.",
    techStack: [],
    hasWebsite: false,
    analysis: null,
  },
  {
    id: "fit002",
    name: "FitCore Wellness Studio",
    domain: "fitcorewellness.ca",
    website: "https://fitcorewellness.ca",
    logo: null,
    city: "Ottawa",
    region: "Ontario",
    country: "Canada",
    niche: "Fitness",
    size: "1-10",
    revenue: "0-500K",
    linkedin: null,
    description: "Yoga and fitness studio in Ottawa. Built on Squarespace but hasn't been updated since 2021. Class schedule is outdated and contact form broken.",
    techStack: ["Squarespace", "Google Analytics"],
    hasWebsite: true,
    analysis: null,
  },
];
