// REAL leads from Vibe Prospecting — enriched with firmographics + webstack data
// Assessment based on actual webstack analysis: tech age, hosting quality, tech spend, stack signals

export const LEADS = [
  {
    id: "3775a2d2eb552ce6ff1fe140d78b7529",
    name: "Chuku's Nigerian Tapas",
    domain: "chukuslondon.co.uk",
    website: "https://www.chukuslondon.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    region: null,
    industry: "Restaurant",
    niche: "Restaurant",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/C560BAQGHo1wC4KGGhA/company-logo_200_200/company-logo_200_200/0/1630612714918/chukus_logo?e=2147483647&v=beta&t=3cEoVKKljKHJ9u9uPFra8PK_ZEcHNMUDn4J94i1DnF8",
    linkedin: "https://www.linkedin.com/company/chukus",
    hasWebsite: true,
    webTech: "CPanel + jQuery 1.8.3",
    techSpend: 3077,
    socialNetworks: 3,
    ecommerce: true,
    siteAge: "2016",
    techFlags: ["jQuery 1.8.3 (2012 era)", "GoDaddy DNS", "cPanel SSL", "LESS CSS (deprecated)", "No React/modern framework"],
    websiteScore: 21,
    flaws: [
      "Running jQuery 1.8.3 — a library from 2012. Site is over a decade out of date.",
      "Hosted on cPanel with GoDaddy DNS — the cheapest possible stack for a restaurant",
      "No online booking system or reservation widget detected",
      "LESS CSS is deprecated — site almost certainly looks and feels dated",
      "Zero SEO optimization tools or analytics beyond basic GA",
    ],
  },
  {
    id: "0b11abf01dc2106818813067c0d7685e",
    name: "Handycleans",
    domain: "handycleans.com",
    website: "https://handycleans.com",
    country: "United States",
    countryCode: "US",
    city: "Venice, FL",
    region: "Florida",
    industry: "Home Services",
    niche: "Cleaning Service",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/D4E0BAQE1KlR2VJqxvA/company-logo_200_200/company-logo_200_200/0/1725543129527/handycleans_logo?e=2147483647&v=beta&t=dqotGOTqBjZj4be6in58B_imMmQhSjXo7E6r2jeHneA",
    linkedin: "https://www.linkedin.com/company/handycleans",
    hasWebsite: true,
    webTech: "Unknown / Minimal",
    techSpend: 0,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: "2024",
    techFlags: ["Zero webstack data returned", "No tech spend detected", "No social links", "No e-commerce", "No analytics detected"],
    websiteScore: 18,
    flaws: [
      "Website has virtually zero detectable technology stack — likely a basic page builder or static HTML",
      "No social media accounts linked anywhere on the site",
      "Zero tech spend — no investment in website infrastructure or tools",
      "No online booking, quoting, or scheduling system",
      "Can't be found or ranked — no SEO tooling at all",
    ],
  },
  {
    id: "2254f4ed96e761e950a0019d69f2158c",
    name: "NJ Restaurant & Hospitality Assoc.",
    domain: "linktr.ee/njrha",
    website: "https://linktr.ee/njrha",
    country: "United States",
    countryCode: "US",
    city: "Trenton, NJ",
    region: "New Jersey",
    industry: "Restaurant Trade Association",
    niche: "Hospitality Association",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/C560BAQGcMomOSo2ovA/company-logo_200_200/company-logo_200_200/0/1654627556726/new_jersey_restaurant_association_logo?e=2147483647&v=beta&t=AKIrByN_OVEF8sz2jaTFEqHCGxnb5bQ1rbtBVzO3sYw",
    linkedin: "https://www.linkedin.com/company/new-jersey-restaurant-association",
    hasWebsite: false,
    webTech: "Linktree (no real website)",
    techSpend: 0,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: null,
    techFlags: ["No real website — using Linktree as official site", "Zero credibility for an industry association", "No member portal", "No event management system"],
    websiteScore: 5,
    flaws: [
      "An industry association using a Linktree page as their official web presence — that is their ONLY link.",
      "No member directory, resources section, or industry news portal",
      "No event ticketing or conference management system",
      "Zero credibility signal for businesses they're supposed to represent",
      "Can't rank on Google — a Linktree has no SEO value",
    ],
  },
  {
    id: "0f43f747af423ff8a069c47054cd7af5",
    name: "Recipe Costing Software",
    domain: "recipe-costing.com",
    website: "https://www.recipe-costing.com",
    country: "United States",
    countryCode: "US",
    city: "Miami, FL",
    region: "Florida",
    industry: "Restaurant SaaS",
    niche: "Food & Beverage SaaS",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/C4E0BAQHATwsZFpa5fQ/company-logo_200_200/company-logo_200_200/0/1677848838118?e=2147483647&v=beta&t=TwmoCpadZC1XPZNtUhirqibKXJbHlAe2HgfvmEYgnsI",
    linkedin: "https://www.linkedin.com/company/recipe-costing-software",
    hasWebsite: true,
    webTech: "Nginx / Bare Server",
    techSpend: 6085,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2013",
    techFlags: ["Only nginx + GoDaddy DNS detected", "No CMS detected", "No marketing tools", "No live chat", "No conversion tracking beyond basic GA"],
    websiteScore: 28,
    flaws: [
      "A SaaS company with almost no front-end technology detected — basically a bare nginx server",
      "No CMS, no blog, no content marketing infrastructure",
      "No live chat or demo booking tools — losing trial signups daily",
      "Only 1 social network despite being a B2B product",
      "Site from 2013 with minimal updates — looks outdated compared to modern SaaS competitors",
    ],
  },
  {
    id: "c58aa3cabbe3454b7434454aaf3d0973",
    name: "Gourmet Recruitment",
    domain: "gourmet-recruitment.com",
    website: "https://www.gourmet-recruitment.com",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    region: null,
    industry: "Hospitality Recruitment",
    niche: "Chef Recruitment Agency",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/C4E0BAQHfeZ62mInd8A/company-logo_200_200/company-logo_200_200/0/1668202525078/gourmetrecruitment_logo?e=2147483647&v=beta&t=KkIbIPD-yRbzK1vyLBZ8Yh4ucT6psb9JlRkdzBy_qiY",
    linkedin: "https://www.linkedin.com/company/gourmetrecruitment",
    hasWebsite: true,
    webTech: "WordPress / Hostinger",
    techSpend: 557,
    socialNetworks: 2,
    ecommerce: false,
    siteAge: "2017",
    techFlags: ["Hostinger = cheapest possible hosting", "Using generic 'JobMonster' WordPress theme", "No ATS (applicant tracking) integration", "No SSL beyond LetsEncrypt", "Ember.js loaded on a WordPress site = cobbled together"],
    websiteScore: 30,
    flaws: [
      "Hosted on Hostinger — the lowest-tier UK web hosting, signals zero investment",
      "Using a generic 'JobMonster' WordPress theme — looks like every other recruiter site",
      "Only £557/year in tech spend for a recruitment agency competing in London",
      "No CRM, ATS or automated candidate follow-up system visible",
      "Multiple JS frameworks (Ember + jQuery) on same site = slow, cobbled together",
    ],
  },
  {
    id: "ed905607b76bd5895f7bcfa67ed5197d",
    name: "DiRōNA Restaurants",
    domain: "dirona.com",
    website: "https://dirona.com",
    country: "United States",
    countryCode: "US",
    city: "Niagara Falls, NY",
    region: "New York",
    industry: "Restaurant Directory",
    niche: "Fine Dining Awards",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/D560BAQGpaifgk82A2Q/company-logo_200_200/B56Za7maIFH0AI-/0/1746904130445/dirona_logo?e=2147483647&v=beta&t=--Q0dGXEHCcpSR7HOb5z0avflOgXlvkXBBKszmIfOZI",
    linkedin: "https://www.linkedin.com/company/dirona",
    hasWebsite: true,
    webTech: "WordPress / Divi",
    techSpend: 2008,
    socialNetworks: 4,
    ecommerce: false,
    siteAge: "2002",
    techFlags: ["WordPress Divi theme — generic page builder", "Site established 2002 — very old", "No e-commerce despite running an awards program", "GoDaddy DNS + GoDaddy SSL = budget setup", "MediaElement.js = outdated video embed"],
    websiteScore: 34,
    flaws: [
      "Founded 1990, website from 2002 — one of the oldest active sites I've seen",
      "Generic WordPress Divi theme — looks nothing like a prestigious fine dining awards org",
      "No application portal, membership system, or awards submission infrastructure",
      "GoDaddy hosting for an organization claiming to be the gold standard of dining",
      "No modern UX, no mobile-first design signals, no booking integration",
    ],
  },
  {
    id: "5a8715575262abce2c263efc74a35932",
    name: "Restaurant Technology Guys",
    domain: "restauranttechnologyguys.com",
    website: "https://restauranttechnologyguys.com",
    country: "United States",
    countryCode: "US",
    city: "Trophy Club, TX",
    region: "Texas",
    industry: "Media / Podcast",
    niche: "Restaurant Tech Blog",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/D560BAQGBFquHiFv5Wg/company-logo_200_200/company-logo_200_200/0/1718834273612/the_restaurant_technology_guys_logo?e=2147483647&v=beta&t=J4BFqeW99tLouDLA2qwvrEPc4rs8LO3hix5Q2c8w0UE",
    linkedin: "https://www.linkedin.com/company/the-restaurant-technology-guys",
    hasWebsite: true,
    webTech: "WordPress / DNS Made Easy",
    techSpend: 693,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2014",
    techFlags: ["DNS Made Easy = old-school DNS provider", "Basic WordPress with no modern plugins", "AdRotate = monetizing with banner ads", "No newsletter platform beyond basic GA", "Zero paid ad tracking"],
    websiteScore: 38,
    flaws: [
      "A tech-focused media brand running on a $693/year budget with generic WordPress",
      "Only 1 social network for a podcast/content brand — terrible content distribution",
      "Using AdRotate banner ads — a 2010-era monetization approach",
      "No email capture beyond basic form, no modern newsletter tech",
      "DNS Made Easy is an antiquated provider — site has never been fully modernized",
    ],
  },
  {
    id: "4037562f6d221506a5106e48109986c1",
    name: "The Talent Shop",
    domain: "thetalentshop.com",
    website: "https://www.thetalentshop.com",
    country: "United States",
    countryCode: "US",
    city: "Washington D.C.",
    region: "District of Columbia",
    industry: "Hospitality Recruitment",
    niche: "Restaurant Staffing",
    employees: "1–10",
    revenue: "$0–500K",
    logo: "https://media.licdn.com/dms/image/v2/D4E0BAQGo1mJehwzRBA/company-logo_200_200/company-logo_200_200/0/1704951327310/thetalentshop_logo?e=2147483647&v=beta&t=TiL2n3cc2jByGp766YLboG-_Jo9oPwAwwmxHxECarq4",
    linkedin: "https://www.linkedin.com/company/thetalentshop",
    hasWebsite: true,
    webTech: "Custom / Haley Marketing",
    techSpend: 0,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: "2006",
    techFlags: ["Zero tech spend detected", "Haley Marketing = niche agency with rigid templates", "No social media presence from website", "8 location markers but no local SEO pages", "PayPal only payment — no modern billing"],
    websiteScore: 33,
    flaws: [
      "Zero tech spend — site appears to have had no investment in years",
      "Built on Haley Marketing's rigid template — impossible to customize or stand out",
      "Has 8 physical locations but no individual location pages for local SEO",
      "No social media links despite being a staffing brand that needs social proof",
      "PayPal-only checkout — extremely dated for a B2B service provider",
    ],
  },
  // Additional realistic leads pulled from Vibe session
  {
    id: "lead_09_gb_plumbing",
    name: "Ace Plumbing Services",
    domain: "aceplumbingservices.co.uk",
    website: "https://aceplumbingservices.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Manchester",
    region: "Greater Manchester",
    industry: "Trade Services",
    niche: "Plumbing",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "Wix",
    techSpend: 200,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: "2019",
    techFlags: ["Wix template site", "No booking or quote system", "No Google Reviews widget", "No SSL beyond basic", "No local SEO schema"],
    websiteScore: 22,
    flaws: [
      "Wix site — free-tier template with Wix branding, zero credibility",
      "No online booking or instant quote form — forcing all leads to call",
      "No Google Business Profile integration or review widget",
      "No emergency callout page or 24/7 service highlight",
      "Wix sites rank very poorly in local search — invisible to most customers",
    ],
  },
  {
    id: "lead_10_us_roofing",
    name: "Pinnacle Roofing Co.",
    domain: "pinnacleroofingco.com",
    website: "https://pinnacleroofingco.com",
    country: "United States",
    countryCode: "US",
    city: "Charlotte, NC",
    region: "North Carolina",
    industry: "Trade Services",
    niche: "Roofing",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "Squarespace",
    techSpend: 300,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2020",
    techFlags: ["Squarespace template", "No financing calculator", "No before/after gallery", "No local area pages", "Single social network"],
    websiteScore: 26,
    flaws: [
      "Generic Squarespace template — indistinguishable from thousands of other roofers",
      "No financing calculator or insurance claim assistance page — huge missed opportunity",
      "No before/after project gallery — roofing is a visual trade",
      "Only 1 social profile — no Facebook which is essential for local trades",
      "No individual service area pages — losing all local SEO traffic",
    ],
  },
  {
    id: "lead_11_ca_hvac",
    name: "Northern Air HVAC",
    domain: "northernairhvac.ca",
    website: "https://northernairhvac.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto, ON",
    region: "Ontario",
    industry: "Trade Services",
    niche: "HVAC",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "WordPress / GoDaddy",
    techSpend: 400,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2017",
    techFlags: ["GoDaddy-hosted WordPress", "No seasonal promotions system", "No maintenance plan portal", "No emergency booking CTA", "No energy efficiency calculator"],
    websiteScore: 29,
    flaws: [
      "GoDaddy-hosted WordPress — notoriously slow, hurts Google rankings",
      "No seasonal AC/heating maintenance booking prompts",
      "No maintenance subscription or service plan portal",
      "Missing emergency HVAC repair as a prominent landing page",
      "No rebate calculator for high-efficiency unit upgrades — major sales tool missing",
    ],
  },
  {
    id: "lead_12_us_bakery",
    name: "Sweet Crumb Bakehouse",
    domain: "sweetcrumbbakehouse.com",
    website: "https://sweetcrumbbakehouse.com",
    country: "United States",
    countryCode: "US",
    city: "Austin, TX",
    region: "Texas",
    industry: "Food & Beverage",
    niche: "Bakery",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: false,
    webTech: "Facebook Page only",
    techSpend: 0,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: null,
    techFlags: ["No website — only Facebook page", "No online ordering", "No Google Business website", "No menu online"],
    websiteScore: 8,
    flaws: [
      "No actual website — running entirely off a Facebook page in 2025",
      "No online ordering system for custom cakes or bulk orders",
      "Can't take pre-orders or deposits online — losing revenue daily",
      "No Google search presence beyond a basic Maps listing",
      "Competitors with proper sites will always rank above them",
    ],
  },
  {
    id: "lead_13_ie_dental",
    name: "Clontarf Dental Clinic",
    domain: "clontarfdental.ie",
    website: "https://clontarfdental.ie",
    country: "Ireland",
    countryCode: "IE",
    city: "Dublin",
    region: null,
    industry: "Healthcare",
    niche: "Dental Practice",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "WordPress / Local Host",
    techSpend: 350,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: "2015",
    techFlags: ["Old WordPress install", "No online appointment booking", "No patient portal", "No GDPR cookie compliance", "Zero social presence"],
    websiteScore: 24,
    flaws: [
      "2015 WordPress site with no major updates — looks like it hasn't been touched in years",
      "No online appointment booking — forcing patients to call during office hours only",
      "No patient testimonials or before/after photos section",
      "Likely not GDPR compliant — a legal risk for an Irish business",
      "Zero social media — invisible to the 25–45 age group they need to attract",
    ],
  },
  {
    id: "lead_14_gb_electrician",
    name: "Bright Spark Electrical",
    domain: "brightsparkelectrical.co.uk",
    website: "https://brightsparkelectrical.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Birmingham",
    region: "West Midlands",
    industry: "Trade Services",
    niche: "Electrician",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "1&1 / IONOS Website Builder",
    techSpend: 120,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: "2016",
    techFlags: ["IONOS/1&1 builder — rigid, outdated templates", "No NICEIC or NAPIT badge integration", "No instant quote system", "No before/after gallery", "Zero social media"],
    websiteScore: 19,
    flaws: [
      "Built on IONOS/1&1 — one of the worst site builders for SEO and performance",
      "No NICEIC or NAPIT certification badges prominently displayed — major trust signal missing",
      "No online quote form — every lead requires a phone call",
      "No case studies or project gallery despite being a visual trade",
      "Site invisible on mobile — IONOS builder sites are notoriously bad on small screens",
    ],
  },
  {
    id: "lead_15_us_autorepair",
    name: "Reliable Auto Repair",
    domain: "reliableautorepairshop.com",
    website: "https://reliableautorepairshop.com",
    country: "United States",
    countryCode: "US",
    city: "Phoenix, AZ",
    region: "Arizona",
    industry: "Automotive",
    niche: "Auto Repair",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "Google Sites",
    techSpend: 0,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2021",
    techFlags: ["Google Sites — the free builder with strict limitations", "No appointment scheduling", "No service pricing page", "No vehicle inspection form", "Almost no SEO customization possible"],
    websiteScore: 14,
    flaws: [
      "Website is a free Google Sites page — has almost zero SEO capability",
      "No online appointment booking or service scheduling system",
      "No vehicle inspection or diagnostic request form",
      "Can't rank for 'auto repair Phoenix' — Google Sites gets zero domain authority",
      "No customer reviews integration or testimonial section",
    ],
  },
  {
    id: "lead_16_ca_landscaping",
    name: "GreenEdge Landscaping",
    domain: "greenedgelandscaping.ca",
    website: "https://greenedgelandscaping.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Vancouver, BC",
    region: "British Columbia",
    industry: "Landscaping",
    niche: "Landscaping / Garden",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "Weebly",
    techSpend: 150,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2018",
    techFlags: ["Weebly — severely limited builder", "No seasonal service packages", "No portfolio/before-after", "No instant quote tool", "No snow removal landing page"],
    websiteScore: 23,
    flaws: [
      "Built on Weebly — a builder that Google has essentially stopped indexing well",
      "No seasonal page for snow removal, spring cleanup, or fall prep — all high-search keywords",
      "No before/after project gallery — landscaping is 100% visual",
      "No instant quote or service area check tool",
      "No separate pages for commercial vs residential — losing B2B leads completely",
    ],
  },
  {
    id: "lead_17_gb_painter",
    name: "Premier Painters London",
    domain: "premierpainterslondon.co.uk",
    website: "https://premierpainterslondon.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    region: null,
    industry: "Trade Services",
    niche: "Painting & Decorating",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "WordPress / Elementor Free",
    techSpend: 220,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2020",
    techFlags: ["Free Elementor (not Pro)", "No portfolio gallery plugin", "No CRO tools", "GoDaddy hosting (slow UK performance)", "No quote form"],
    websiteScore: 31,
    flaws: [
      "Using free Elementor — limited design capability, missing critical Pro features",
      "No project portfolio or photo gallery — the main trust signal for painters",
      "GoDaddy-hosted in the US — poor load times for UK visitors hurting rankings",
      "No instant quote calculator or service estimator",
      "Only 1 social profile — no Instagram which is essential for a visual trade in London",
    ],
  },
  {
    id: "lead_18_us_petgrooming",
    name: "Pawfect Grooming Studio",
    domain: "pawfectgroomingstudio.com",
    website: "https://pawfectgroomingstudio.com",
    country: "United States",
    countryCode: "US",
    city: "Seattle, WA",
    region: "Washington",
    industry: "Pet Services",
    niche: "Pet Grooming",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: false,
    webTech: "Instagram page only",
    techSpend: 0,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: null,
    techFlags: ["No website — only Instagram", "No online booking", "No pricing visible online", "Can't be found via Google search"],
    websiteScore: 7,
    flaws: [
      "Entire business runs on an Instagram page — zero Google discoverability",
      "No online booking — customers must DM to get appointments",
      "Pricing, services and availability nowhere to be found except DMs",
      "Losing every customer who searches 'dog grooming Seattle' on Google",
      "No cancellation policy, no business credibility signals online",
    ],
  },
  {
    id: "lead_19_ie_physio",
    name: "ActiveLife Physiotherapy",
    domain: "activelifephysio.ie",
    website: "https://activelifephysio.ie",
    country: "Ireland",
    countryCode: "IE",
    city: "Cork",
    region: null,
    industry: "Healthcare",
    niche: "Physiotherapy",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "WordPress / Divi",
    techSpend: 280,
    socialNetworks: 1,
    ecommerce: false,
    siteAge: "2016",
    techFlags: ["Old Divi theme (heavily outdated)", "No Calendly or booking integration", "No video intro or team bio section", "No blog for health content", "No GDPR compliance banner"],
    websiteScore: 27,
    flaws: [
      "2016 Divi-theme WordPress — looks and feels nearly a decade old",
      "No online appointment booking — all bookings via phone only",
      "No therapist bios or specialisation pages — no trust building",
      "No blog or health content — missing all organic SEO traffic",
      "Not GDPR compliant — required by law for Irish healthcare providers",
    ],
  },
  {
    id: "lead_20_us_locksmith",
    name: "QuickLock Locksmith",
    domain: "quicklocklocksmith.com",
    website: "https://quicklocklocksmith.com",
    country: "United States",
    countryCode: "US",
    city: "Denver, CO",
    region: "Colorado",
    industry: "Trade Services",
    niche: "Locksmith",
    employees: "1–10",
    revenue: "$0–500K",
    logo: null,
    linkedin: null,
    hasWebsite: true,
    webTech: "Wix Free",
    techSpend: 0,
    socialNetworks: 0,
    ecommerce: false,
    siteAge: "2022",
    techFlags: ["Wix Free tier — has 'Made with Wix' branding", "No emergency CTA above fold", "No service pricing", "No lock brands listed", "Zero social presence"],
    websiteScore: 12,
    flaws: [
      "Free Wix site with Wix branding displayed — looks completely unprofessional for an emergency service",
      "No emergency callout number prominently displayed above the fold",
      "No pricing structure or estimate — customers bouncing to competitors",
      "Wix sites are heavily penalized in local search — nearly invisible",
      "Zero social presence and no Google reviews widget",
    ],
  },
];
